### ISSUE TITLE
高版本导致失效

### ISSUE THREAD

**Issue by proxiti** [Cormor/ComposeOverscroll#2]
以下依赖
androidx.compose.foundation.gestures.scrollable
来自于包
androidx.compose.foundation:foundation:1.3.1

1.3.1 版本会导致动画不正常，1.2.0 版本正常

**Comment by Cormor** [comment]
应当是你有版本引用到更高的1.4.0+版本的compose了，1.3.1版本测试可用是正常的。
建议使用gradle dependency确认下哪个依赖升级到了最新的compose版本，1.4.0-alpha02之后的嵌套手势都有问题，详见issue:
https://issuetracker.google.com/issues/276682419

可以升级至经测试最高可用的1.3.3版本。

**Comment by Cormor** [comment]
已解决，经验证最高支持至最新的1.5.0稳定版。
